# RECOLECCIÓN Y LIMPIEZA DE DATA

En este notebook realizaremos la recolección y limpieza de los datos que se están guardando diariamente en las carpetas buses_outputs y metro_outputs. Con ello, uniremos los datos correspondientes a las micros con los del archivo JSON guardado en la carpeta data.

In [1]:
# librerías a utilizar
import pandas as pd
import json
from pathlib import Path
from datetime import datetime, timedelta, date

In [2]:
# Creamos funcion que añada nuevos datos al dataframe unificado 
def anadir_datos(nuevos_datos, ruta):
    # Dataframe de los datos nuevos
    df_nuevos_datos = pd.concat(nuevos_datos, ignore_index=True)
    # Si ya tenemos datos en dicha fecha:
    if ruta.exists():
        # Abrimos los datos ya existentes
        datos_guardados = pd.read_csv(ruta)
        # Les añadimos los nuevos datos recolectados
        nuevo_csv = pd.concat([datos_guardados, df_nuevos_datos], ignore_index=True)
        # volvemos a guardar en la ruta que estaban los datos ya existentes
        nuevo_csv.to_csv(ruta, index=False, encoding='utf-8')
    else:
        # si no teníamos datos en dicha fecha
        nuevo_csv = df_nuevos_datos
        # agregamos los datos a la ruta 
        nuevo_csv.to_csv(ruta, index=False, encoding='utf-8')
    return nuevo_csv

In [3]:
# Creamos las rutas a la carpeta de la micro y metro:
carpeta_bus = Path('buses_outputs')
carpeta_metro = Path('metro_outputs')
# Creamos las carpetas para guardar los datos:
csv_unificado_micro = Path('csv_unificado_micro')
csv_unificado_micro.mkdir(exist_ok=True)
csv_unificado_metro = Path('csv_unificado_metro')
csv_unificado_metro.mkdir(exist_ok=True)
# Determinamos ruta para CSV's unificados
ruta_unificada_micro = csv_unificado_micro / 'datos_unificados_micro.csv'
ruta_unificada_metro = csv_unificado_metro / 'datos_unificados_metro.csv'
# Determinamos formato de tiempo que tienen los distintos csv
tiempo_hora_minuto = '%d-%m-%Y-%H-%M'
# Determinamos fecha inicial de extracción
fecha_inicio = date(2025, 10, 12)
print(f'La fecha de inicio para la extracción de datos es: {fecha_inicio}')

La fecha de inicio para la extracción de datos es: 2025-10-12

In [4]:
# Fecha en la que empezamos la extracción
fecha_actual = fecha_inicio
# Para los datos de la micro
info_df_diario = []
# Enlistamos los datos de 'buses_outputs'
recorrer = list(carpeta_bus.glob('*csv'))
# diccionario micros para ver si faltan agregar datos de un día
micro_dict = dict()
# Los recorremos para empezar a crear los DataFrame
for i in range(len(recorrer)): 
    # Ponemos en el formato de fecha de los datos extraídos: día, mes y año
    fecha_actual_formato = fecha_actual.strftime('%d-%m-%Y')
    print(f'Recolectando datos de las micros del día {fecha_actual_formato}')
    # Nos quedamos con la fecha del archivo que estamos leyendo
    archivo_fecha = recorrer[i].stem[6:]
    try: 
        # Si el archivo de esta iteración es valor de la llave de la fecha actual
        if archivo_fecha in micro_dict[fecha_actual_formato]:
            continue
        else:
            # si no lo es, lo añadimos
            micro_dict[fecha_actual_formato].add(archivo_fecha)
    # Si esa llave no existía (no habíamos revisado nada de ese día), la creamos
    except KeyError:
        # La creamos en un set para hacer más fácil su búsqueda después
        micro_dict[fecha_actual_formato] = {f'{archivo_fecha}'}
    # Convertimos la fecha del archivo al formato tiempo_hora_minuto
    hora_minuto = datetime.strptime(archivo_fecha, tiempo_hora_minuto)
    # Leemos el csv actual
    print(f'Recolectando datos de las: {hora_minuto.hour:02d}:{hora_minuto.minute:02d}')
    dataframe_archivo = pd.read_csv(recorrer[i], encoding='utf-8')
    # Creamos una columna que incluya la hora y el minuto
    dataframe_archivo['Hour_minute'] = f'{hora_minuto.hour:02d}:{hora_minuto.minute:02d}'
    # añadimos el df creado a nuestra lista de información por día
    info_df_diario.append(dataframe_archivo)
    try:
        # Si la fecha actual no está en el siguiente elemento, se acabaron los datos del
        # día y debemos guardar todo lo recolectado
        if fecha_actual_formato not in recorrer[i+1].stem:
            # creamos la ruta donde guardaremos los datos
            anadir_datos(info_df_diario, ruta_unificada_micro)
            # Vaciamos la info del día pues vamos a cambiarlo
            info_df_diario = []
            # Pasamos al día siguiente
            fecha_actual += timedelta(days=1)

    # Si llegamos al final de la lista no se podrá hacer i+1
    except IndexError as error:
        # creamos ruta para el último día de datos
        anadir_datos(info_df_diario, ruta_unificada_micro)
        # Vaciamos info del día
        info_df_diario = []

Recolectando datos de las micros del día 12-10-2025
Recolectando datos de las: 19:01
Recolectando datos de las micros del día 12-10-2025
Recolectando datos de las: 20:00
Recolectando datos de las micros del día 12-10-2025
Recolectando datos de las: 22:00
Recolectando datos de las micros del día 13-10-2025
Recolectando datos de las: 06:00
Recolectando datos de las micros del día 13-10-2025
Recolectando datos de las: 08:00
Recolectando datos de las micros del día 13-10-2025
Recolectando datos de las: 10:00
Recolectando datos de las micros del día 13-10-2025
Recolectando datos de las: 12:00
Recolectando datos de las micros del día 13-10-2025
Recolectando datos de las: 14:00
Recolectando datos de las micros del día 13-10-2025
Recolectando datos de las: 16:00
Recolectando datos de las micros del día 13-10-2025
Recolectando datos de las: 18:00
Recolectando datos de las micros del día 13-10-2025
Recolectando datos de las: 20:00
Recolectando datos de las micros del día 13-10-2025
Recolectando datos de las: 22:00
Recolectando datos de las micros del día 14-10-2025
Recolectando datos de las: 06:00
Recolectando datos de las micros del día 14-10-2025
Recolectando datos de las: 08:00
Recolectando datos de las micros del día 14-10-2025
Recolectando datos de las: 10:00
Recolectando datos de las micros del día 14-10-2025
Recolectando datos de las: 12:00
Recolectando datos de las micros del día 14-10-2025
Recolectando datos de las: 14:00
Recolectando datos de las micros del día 14-10-2025
Recolectando datos de las: 16:00
Recolectando datos de las micros del día 14-10-2025
Recolectando datos de las: 18:00
Recolectando datos de las micros del día 14-10-2025
Recolectando datos de las: 20:00
Recolectando datos de las micros del día 14-10-2025
Recolectando datos de las: 22:00
Recolectando datos de las micros del día 15-10-2025
Recolectando datos de las: 06:00
Recolectando datos de las micros del día 15-10-2025
Recolectando datos de las: 08:00
Recolectando datos de las micros del día 15-10-2025
Recolectando datos de las: 10:00
Recolectando datos de las micros del día 15-10-2025
Recolectando datos de las: 12:00
Recolectando datos de las micros del día 15-10-2025
Recolectando datos de las: 14:00
Recolectando datos de las micros del día 15-10-2025
Recolectando datos de las: 16:00
Recolectando datos de las micros del día 15-10-2025
Recolectando datos de las: 18:00
Recolectando datos de las micros del día 15-10-2025
Recolectando datos de las: 20:00
Recolectando datos de las micros del día 15-10-2025
Recolectando datos de las: 22:00
Recolectando datos de las micros del día 16-10-2025
Recolectando datos de las: 06:00
Recolectando datos de las micros del día 16-10-2025
Recolectando datos de las: 08:00
Recolectando datos de las micros del día 16-10-2025
Recolectando datos de las: 10:00
Recolectando datos de las micros del día 16-10-2025
Recolectando datos de las: 12:00
Recolectando datos de las micros del día 16-10-2025
Recolectando datos de las: 14:00
Recolectando datos de las micros del día 16-10-2025
Recolectando datos de las: 16:00
Recolectando datos de las micros del día 16-10-2025
Recolectando datos de las: 18:00
Recolectando datos de las micros del día 16-10-2025
Recolectando datos de las: 20:00
Recolectando datos de las micros del día 16-10-2025
Recolectando datos de las: 22:00
Recolectando datos de las micros del día 17-10-2025
Recolectando datos de las: 06:00
Recolectando datos de las micros del día 17-10-2025
Recolectando datos de las: 08:40
Recolectando datos de las micros del día 17-10-2025
Recolectando datos de las: 10:00
Recolectando datos de las micros del día 17-10-2025
Recolectando datos de las: 12:00
Recolectando datos de las micros del día 17-10-2025
Recolectando datos de las: 14:00
Recolectando datos de las micros del día 17-10-2025
Recolectando datos de las: 16:00
Recolectando datos de las micros del día 17-10-2025
Recolectando datos de las: 18:00
Recolectando datos de las micros del día 17-10-2025
Recolectando datos de las: 20:00
Recolectando datos de las micros del día 17-10-2025
Recolectando datos de las: 22:00
Recolectando datos de las micros del día 18-10-2025
Recolectando datos de las: 06:00
Recolectando datos de las micros del día 18-10-2025
Recolectando datos de las: 08:00
Recolectando datos de las micros del día 18-10-2025
Recolectando datos de las: 10:00
Recolectando datos de las micros del día 18-10-2025
Recolectando datos de las: 12:00
Recolectando datos de las micros del día 18-10-2025
Recolectando datos de las: 14:00
Recolectando datos de las micros del día 18-10-2025
Recolectando datos de las: 16:00
Recolectando datos de las micros del día 18-10-2025
Recolectando datos de las: 18:00
Recolectando datos de las micros del día 18-10-2025
Recolectando datos de las: 20:00
Recolectando datos de las micros del día 18-10-2025
Recolectando datos de las: 22:00
Recolectando datos de las micros del día 19-10-2025
Recolectando datos de las: 06:00
Recolectando datos de las micros del día 19-10-2025
Recolectando datos de las: 08:00
Recolectando datos de las micros del día 19-10-2025
Recolectando datos de las: 10:00
Recolectando datos de las micros del día 19-10-2025
Recolectando datos de las: 12:00
Recolectando datos de las micros del día 19-10-2025
Recolectando datos de las: 14:00
Recolectando datos de las micros del día 19-10-2025
Recolectando datos de las: 16:00
Recolectando datos de las micros del día 19-10-2025
Recolectando datos de las: 18:00
Recolectando datos de las micros del día 19-10-2025
Recolectando datos de las: 20:00
Recolectando datos de las micros del día 19-10-2025
Recolectando datos de las: 22:00
Recolectando datos de las micros del día 20-10-2025
Recolectando datos de las: 06:00
Recolectando datos de las micros del día 20-10-2025
Recolectando datos de las: 08:00
Recolectando datos de las micros del día 20-10-2025
Recolectando datos de las: 10:00
Recolectando datos de las micros del día 20-10-2025
Recolectando datos de las: 12:00
Recolectando datos de las micros del día 20-10-2025
Recolectando datos de las: 14:00
Recolectando datos de las micros del día 20-10-2025
Recolectando datos de las: 18:00
Recolectando datos de las micros del día 20-10-2025
Recolectando datos de las: 20:00
Recolectando datos de las micros del día 20-10-2025
Recolectando datos de las: 22:00

In [5]:
# Añadimos los datos diarios del metro
df_metro_diario = []
# Partimos con la fecha de inicio
fecha_actual_metro = fecha_inicio
datos = list(carpeta_metro.glob('*csv'))
# creamos diccionario para ver si faltan agregar los datos de un día
metro_dict = dict()
for i in range(len(datos)):
    # Trabajamos la fecha según como salen los datos de carpeta_metro
    formato_metro = fecha_actual_metro.strftime('%d-%m-%Y')
    print(f'Recolectando datos del metro del día: {formato_metro}')
    fecha_a_revisar = datos[i].stem[6:]
    try: 
        if fecha_a_revisar in metro_dict[formato_metro]:
            continue
        else:
            metro_dict[formato_metro].add(fecha_a_revisar)
    except KeyError:
        metro_dict[formato_metro] = {f'{fecha_a_revisar}'}
    hora_minuto = datetime.strptime(fecha_a_revisar, tiempo_hora_minuto)
    print(f'Recolectando datos de las: {hora_minuto.hour:02d}:{hora_minuto.minute:02d}')
    dataframe_actual = pd.read_csv(datos[i], encoding='utf-8')
    dataframe_actual['Hora_minuto'] = f'{hora_minuto.hour:02d}:{hora_minuto.minute:02d}'
    df_metro_diario.append(dataframe_actual)
    try:
        # Si la fecha actual no está en el siguiente elemento, se acabaron los datos del
        # día y debemos guardar todo lo recolectado
        if formato_metro not in datos[i+1].stem:
            # creamos la ruta donde guardaremos los datos
            anadir_datos(df_metro_diario, ruta_unificada_metro)
            df_metro_diario = []
            # Sumamos un día a la fecha actual
            fecha_actual_metro += timedelta(days=1)
    # Si llegamos al final de la lista no se podrá hacer i+1
    except IndexError as error:
        # creamos ruta para el último día de datos
        anadir_datos(df_metro_diario, ruta_unificada_metro)
        df_metro_diario = []

Recolectando datos del metro del día: 12-10-2025
Recolectando datos de las: 17:07
Recolectando datos del metro del día: 12-10-2025
Recolectando datos de las: 18:30
Recolectando datos del metro del día: 12-10-2025
Recolectando datos de las: 19:30
Recolectando datos del metro del día: 12-10-2025
Recolectando datos de las: 20:30
Recolectando datos del metro del día: 12-10-2025
Recolectando datos de las: 21:30
Recolectando datos del metro del día: 12-10-2025
Recolectando datos de las: 22:30
Recolectando datos del metro del día: 13-10-2025
Recolectando datos de las: 06:30
Recolectando datos del metro del día: 13-10-2025
Recolectando datos de las: 07:30
Recolectando datos del metro del día: 13-10-2025
Recolectando datos de las: 08:30
Recolectando datos del metro del día: 13-10-2025
Recolectando datos de las: 09:30
Recolectando datos del metro del día: 13-10-2025
Recolectando datos de las: 10:30
Recolectando datos del metro del día: 13-10-2025
Recolectando datos de las: 11:30
Recolectando datos del metro del día: 13-10-2025
Recolectando datos de las: 12:30
Recolectando datos del metro del día: 13-10-2025
Recolectando datos de las: 13:30
Recolectando datos del metro del día: 13-10-2025
Recolectando datos de las: 14:30
Recolectando datos del metro del día: 13-10-2025
Recolectando datos de las: 15:30
Recolectando datos del metro del día: 13-10-2025
Recolectando datos de las: 16:30
Recolectando datos del metro del día: 13-10-2025
Recolectando datos de las: 17:30
Recolectando datos del metro del día: 13-10-2025
Recolectando datos de las: 18:30
Recolectando datos del metro del día: 13-10-2025
Recolectando datos de las: 19:30
Recolectando datos del metro del día: 13-10-2025
Recolectando datos de las: 20:30
Recolectando datos del metro del día: 13-10-2025
Recolectando datos de las: 21:30
Recolectando datos del metro del día: 13-10-2025
Recolectando datos de las: 22:30
Recolectando datos del metro del día: 14-10-2025
Recolectando datos de las: 06:30
Recolectando datos del metro del día: 14-10-2025
Recolectando datos de las: 07:30
Recolectando datos del metro del día: 14-10-2025
Recolectando datos de las: 08:30
Recolectando datos del metro del día: 14-10-2025
Recolectando datos de las: 09:30
Recolectando datos del metro del día: 14-10-2025
Recolectando datos de las: 10:30
Recolectando datos del metro del día: 14-10-2025
Recolectando datos de las: 11:30
Recolectando datos del metro del día: 14-10-2025
Recolectando datos de las: 12:30
Recolectando datos del metro del día: 14-10-2025
Recolectando datos de las: 13:30
Recolectando datos del metro del día: 14-10-2025
Recolectando datos de las: 14:30
Recolectando datos del metro del día: 14-10-2025
Recolectando datos de las: 15:30
Recolectando datos del metro del día: 14-10-2025
Recolectando datos de las: 16:30
Recolectando datos del metro del día: 14-10-2025
Recolectando datos de las: 17:30
Recolectando datos del metro del día: 14-10-2025
Recolectando datos de las: 18:30
Recolectando datos del metro del día: 14-10-2025
Recolectando datos de las: 19:30
Recolectando datos del metro del día: 14-10-2025
Recolectando datos de las: 20:30
Recolectando datos del metro del día: 14-10-2025
Recolectando datos de las: 21:30
Recolectando datos del metro del día: 14-10-2025
Recolectando datos de las: 22:30
Recolectando datos del metro del día: 15-10-2025
Recolectando datos de las: 06:30
Recolectando datos del metro del día: 15-10-2025
Recolectando datos de las: 07:30
Recolectando datos del metro del día: 15-10-2025
Recolectando datos de las: 09:30
Recolectando datos del metro del día: 15-10-2025
Recolectando datos de las: 10:30
Recolectando datos del metro del día: 15-10-2025
Recolectando datos de las: 11:30
Recolectando datos del metro del día: 15-10-2025
Recolectando datos de las: 12:30
Recolectando datos del metro del día: 15-10-2025
Recolectando datos de las: 13:30
Recolectando datos del metro del día: 15-10-2025
Recolectando datos de las: 14:30
Recolectando datos del metro del día: 15-10-2025
Recolectando datos de las: 15:30
Recolectando datos del metro del día: 15-10-2025
Recolectando datos de las: 16:30
Recolectando datos del metro del día: 15-10-2025
Recolectando datos de las: 17:30
Recolectando datos del metro del día: 15-10-2025
Recolectando datos de las: 18:30
Recolectando datos del metro del día: 15-10-2025
Recolectando datos de las: 19:30
Recolectando datos del metro del día: 15-10-2025
Recolectando datos de las: 20:30
Recolectando datos del metro del día: 15-10-2025
Recolectando datos de las: 21:30
Recolectando datos del metro del día: 15-10-2025
Recolectando datos de las: 22:30
Recolectando datos del metro del día: 16-10-2025
Recolectando datos de las: 06:30
Recolectando datos del metro del día: 16-10-2025
Recolectando datos de las: 07:30
Recolectando datos del metro del día: 16-10-2025
Recolectando datos de las: 08:30
Recolectando datos del metro del día: 16-10-2025
Recolectando datos de las: 09:30
Recolectando datos del metro del día: 16-10-2025
Recolectando datos de las: 10:30
Recolectando datos del metro del día: 16-10-2025
Recolectando datos de las: 11:30
Recolectando datos del metro del día: 16-10-2025
Recolectando datos de las: 12:30
Recolectando datos del metro del día: 16-10-2025
Recolectando datos de las: 13:30
Recolectando datos del metro del día: 16-10-2025
Recolectando datos de las: 14:30
Recolectando datos del metro del día: 16-10-2025
Recolectando datos de las: 15:30
Recolectando datos del metro del día: 16-10-2025
Recolectando datos de las: 16:30
Recolectando datos del metro del día: 16-10-2025
Recolectando datos de las: 17:30
Recolectando datos del metro del día: 16-10-2025
Recolectando datos de las: 18:30
Recolectando datos del metro del día: 16-10-2025
Recolectando datos de las: 19:30
Recolectando datos del metro del día: 16-10-2025
Recolectando datos de las: 20:30
Recolectando datos del metro del día: 16-10-2025
Recolectando datos de las: 21:30
Recolectando datos del metro del día: 16-10-2025
Recolectando datos de las: 22:30
Recolectando datos del metro del día: 17-10-2025
Recolectando datos de las: 06:30
Recolectando datos del metro del día: 17-10-2025
Recolectando datos de las: 07:30
Recolectando datos del metro del día: 17-10-2025
Recolectando datos de las: 08:30
Recolectando datos del metro del día: 17-10-2025
Recolectando datos de las: 09:30
Recolectando datos del metro del día: 17-10-2025
Recolectando datos de las: 10:30
Recolectando datos del metro del día: 17-10-2025
Recolectando datos de las: 11:30
Recolectando datos del metro del día: 17-10-2025
Recolectando datos de las: 12:30
Recolectando datos del metro del día: 17-10-2025
Recolectando datos de las: 13:30
Recolectando datos del metro del día: 17-10-2025
Recolectando datos de las: 14:30
Recolectando datos del metro del día: 17-10-2025
Recolectando datos de las: 15:30
Recolectando datos del metro del día: 17-10-2025
Recolectando datos de las: 16:30
Recolectando datos del metro del día: 17-10-2025
Recolectando datos de las: 17:30
Recolectando datos del metro del día: 17-10-2025
Recolectando datos de las: 18:30
Recolectando datos del metro del día: 17-10-2025
Recolectando datos de las: 19:30
Recolectando datos del metro del día: 17-10-2025
Recolectando datos de las: 20:30
Recolectando datos del metro del día: 17-10-2025
Recolectando datos de las: 21:30
Recolectando datos del metro del día: 17-10-2025
Recolectando datos de las: 22:30
Recolectando datos del metro del día: 18-10-2025
Recolectando datos de las: 06:30
Recolectando datos del metro del día: 18-10-2025
Recolectando datos de las: 07:30
Recolectando datos del metro del día: 18-10-2025
Recolectando datos de las: 08:30
Recolectando datos del metro del día: 18-10-2025
Recolectando datos de las: 09:30
Recolectando datos del metro del día: 18-10-2025
Recolectando datos de las: 10:30
Recolectando datos del metro del día: 18-10-2025
Recolectando datos de las: 11:30
Recolectando datos del metro del día: 18-10-2025
Recolectando datos de las: 12:30
Recolectando datos del metro del día: 18-10-2025
Recolectando datos de las: 13:30
Recolectando datos del metro del día: 18-10-2025
Recolectando datos de las: 14:30
Recolectando datos del metro del día: 18-10-2025
Recolectando datos de las: 15:30
Recolectando datos del metro del día: 18-10-2025
Recolectando datos de las: 16:30
Recolectando datos del metro del día: 18-10-2025
Recolectando datos de las: 17:30
Recolectando datos del metro del día: 18-10-2025
Recolectando datos de las: 18:30
Recolectando datos del metro del día: 18-10-2025
Recolectando datos de las: 19:30
Recolectando datos del metro del día: 18-10-2025
Recolectando datos de las: 20:30
Recolectando datos del metro del día: 18-10-2025
Recolectando datos de las: 21:30
Recolectando datos del metro del día: 18-10-2025
Recolectando datos de las: 22:30
Recolectando datos del metro del día: 19-10-2025
Recolectando datos de las: 06:30
Recolectando datos del metro del día: 19-10-2025
Recolectando datos de las: 07:30
Recolectando datos del metro del día: 19-10-2025
Recolectando datos de las: 08:30
Recolectando datos del metro del día: 19-10-2025
Recolectando datos de las: 09:30
Recolectando datos del metro del día: 19-10-2025
Recolectando datos de las: 10:30
Recolectando datos del metro del día: 19-10-2025
Recolectando datos de las: 11:30
Recolectando datos del metro del día: 19-10-2025
Recolectando datos de las: 12:30
Recolectando datos del metro del día: 19-10-2025
Recolectando datos de las: 13:30
Recolectando datos del metro del día: 19-10-2025
Recolectando datos de las: 14:30
Recolectando datos del metro del día: 19-10-2025
Recolectando datos de las: 15:30
Recolectando datos del metro del día: 19-10-2025
Recolectando datos de las: 16:30
Recolectando datos del metro del día: 19-10-2025
Recolectando datos de las: 17:30
Recolectando datos del metro del día: 19-10-2025
Recolectando datos de las: 18:30
Recolectando datos del metro del día: 19-10-2025
Recolectando datos de las: 19:30
Recolectando datos del metro del día: 19-10-2025
Recolectando datos de las: 20:30
Recolectando datos del metro del día: 19-10-2025
Recolectando datos de las: 21:30
Recolectando datos del metro del día: 19-10-2025
Recolectando datos de las: 22:30
Recolectando datos del metro del día: 20-10-2025
Recolectando datos de las: 06:30
Recolectando datos del metro del día: 20-10-2025
Recolectando datos de las: 07:30
Recolectando datos del metro del día: 20-10-2025
Recolectando datos de las: 08:30
Recolectando datos del metro del día: 20-10-2025
Recolectando datos de las: 09:30
Recolectando datos del metro del día: 20-10-2025
Recolectando datos de las: 10:30
Recolectando datos del metro del día: 20-10-2025
Recolectando datos de las: 11:30
Recolectando datos del metro del día: 20-10-2025
Recolectando datos de las: 12:30
Recolectando datos del metro del día: 20-10-2025
Recolectando datos de las: 13:30
Recolectando datos del metro del día: 20-10-2025
Recolectando datos de las: 14:30
Recolectando datos del metro del día: 20-10-2025
Recolectando datos de las: 15:30
Recolectando datos del metro del día: 20-10-2025
Recolectando datos de las: 17:30
Recolectando datos del metro del día: 20-10-2025
Recolectando datos de las: 18:30
Recolectando datos del metro del día: 20-10-2025
Recolectando datos de las: 19:30
Recolectando datos del metro del día: 20-10-2025
Recolectando datos de las: 20:30
Recolectando datos del metro del día: 20-10-2025
Recolectando datos de las: 21:30
Recolectando datos del metro del día: 20-10-2025
Recolectando datos de las: 22:30

In [6]:
# Leemos los csv generados
micro_data = pd.read_csv(ruta_unificada_micro)
metro_data = pd.read_csv(ruta_unificada_metro)
# Eliminamos columnas con coordenadas incorrectas
micro_data.drop(columns=['X', 'Y'], inplace=True)
micro_data.head(3)

,bus_stop_code,route_id,bus_id,meters_distance,min_arrival_time,max_arrival_time,date,Hour_minute
0,PB1013,B12,SKDG-90,7520,16,24,2025-10-12 19:01:28.530087,19:01
1,PB1013,B33,SKPP-55,2951,8,10,2025-10-12 19:01:28.530094,19:01
2,PI725,I10,FLXK-93,2315,7,9,2025-10-12 19:01:30.454781,19:01

In [7]:
# Abrimos el archivo donde tenemos información importantes de los pasajeros
ruta_json = Path('data', 'Paraderos-Santiago-Chile.geojsonl.json')
# Guardamos su informacion en una lista
datos = []
with open(ruta_json, 'r', encoding='utf-8-sig')as f:
    for archivo in f:
        datos.append(json.loads(archivo.strip()))
# creamos un datafraem con los datos de la lista
df_paradero = pd.json_normalize(datos)
# Renombramos columnas que estarán en nuestro DataFrame
df_paradero = df_paradero.rename(columns={'properties.ID': 'id', 
                            'properties.CODINFRA': 'codinfra',
                            'properties.SIMT': 'bus_stop_code',
                            'properties.COMUNA': 'comuna',
                            'properties.NOMBRE_PAR': 'nombre_par',
                            'properties.NSERVICIOS': 'n_servicios',
                            'properties.SERVICIOS': 'servicios',
                            'geometry.coordinates': 'coordinates'})
# Seleccionamos dichas columnas
df_paradero = df_paradero[['id', 'codinfra', 'comuna', 'bus_stop_code', 'nombre_par', 'n_servicios', 'servicios', 'coordinates']]
# Reemplazamos nombres de comunas pues el archivo venía con un encoding incorrecto
df_paradero['comuna'] = df_paradero['comuna'].replace(
    {'CONCHAL�': 'CONCHALÍ',
    'ESTACI�N CENTRAL': 'ESTACIÓN CENTRAL',
    'MAIP�': 'MAIPÚ',
    'PE�ALOL�N': 'PEÑALOLÉN',
    'SAN JOAQU�N': 'SAN JOAQUÍN',
    'SAN RAM�N': 'SAN RAMÓN',
    '�U�OA': 'ÑUÑOA'
    })
df_paradero.head()

,id,codinfra,comuna,bus_stop_code,nombre_par,n_servicios,servicios,coordinates
0,11672,L-35-6-5-OP,PADRE HURTADO,PI1923,Cam. Bajos de Sta. Cruz / esq. El Muelle,1,I35I,"[-70.823088, -33.572525]"
1,11671,L-35-1-67-OP,PADRE HURTADO,PI1935,Cam. Sn. Alberto Hurtado / esq. Sn. Fco de Borja,1,I35I,"[-70.8189, -33.571649]"
2,11674,L-35-5-48-NS,PADRE HURTADO,PI1926,Avenida San Ignacio / esq. Cam. Sn. A. Hurtado,1,I35I,"[-70.818197, -33.57202]"
3,11693,L-35-5-49-SN,PADRE HURTADO,PI1925,Avenida San Ignacio / esq. Cam. Sn. A. Hurtado,1,I35R,"[-70.817967, -33.57187]"
4,11675,L-35-5-54-NS,PADRE HURTADO,PI1927,Avenida San Ignacio / esq. San Alberto,1,I35I,"[-70.816035, -33.574243]"

In [8]:
# Unimos por paradero el JSON y nuestro archivo de micros.
micro_paradero = pd.merge(micro_data, df_paradero, on= 'bus_stop_code', how='inner')
micro_paradero.head()

,bus_stop_code,route_id,bus_id,meters_distance,min_arrival_time,max_arrival_time,date,Hour_minute,id,codinfra,comuna,nombre_par,n_servicios,servicios,coordinates
0,PB1013,B12,SKDG-90,7520,16,24,2025-10-12 19:01:28.530087,19:01,8983,L-6-39-30-OP,QUILICURA,San Ignacio / esq. Galvarino,3,B12I;B12cR;B33I,"[-70.705935, -33.331142]"
1,PB1013,B33,SKPP-55,2951,8,10,2025-10-12 19:01:28.530094,19:01,8983,L-6-39-30-OP,QUILICURA,San Ignacio / esq. Galvarino,3,B12I;B12cR;B33I,"[-70.705935, -33.331142]"
2,PI725,I10,FLXK-93,2315,7,9,2025-10-12 19:01:30.454781,19:01,4883,L-13-68-5-OP,MAIPÚ,Rafael Riesco / esq. 1� Transversal,3,I02I;I10R;I10NR,"[-70.751076, -33.4963]"
3,PI725,I10,FLXJ-25,6384,18,26,2025-10-12 19:01:30.454787,19:01,4883,L-13-68-5-OP,MAIPÚ,Rafael Riesco / esq. 1� Transversal,3,I02I;I10R;I10NR,"[-70.751076, -33.4963]"
4,PI725,I02,FLXY-79,4575,12,16,2025-10-12 19:01:30.454789,19:01,4883,L-13-68-5-OP,MAIPÚ,Rafael Riesco / esq. 1� Transversal,3,I02I;I10R;I10NR,"[-70.751076, -33.4963]"

In [9]:
# Dejamos las coordenadas en columnas Lan y Lon. Eliminamos columna coordinates
micro_paradero[['lan', 'lon']] = pd.DataFrame(micro_paradero['coordinates'].tolist(), index=micro_paradero.index)
micro_paradero.drop(columns=['coordinates'], inplace= True)
micro_paradero.head()

,bus_stop_code,route_id,bus_id,meters_distance,min_arrival_time,max_arrival_time,date,Hour_minute,id,codinfra,comuna,nombre_par,n_servicios,servicios,lan,lon
0,PB1013,B12,SKDG-90,7520,16,24,2025-10-12 19:01:28.530087,19:01,8983,L-6-39-30-OP,QUILICURA,San Ignacio / esq. Galvarino,3,B12I;B12cR;B33I,-70.705935,-33.331142
1,PB1013,B33,SKPP-55,2951,8,10,2025-10-12 19:01:28.530094,19:01,8983,L-6-39-30-OP,QUILICURA,San Ignacio / esq. Galvarino,3,B12I;B12cR;B33I,-70.705935,-33.331142
2,PI725,I10,FLXK-93,2315,7,9,2025-10-12 19:01:30.454781,19:01,4883,L-13-68-5-OP,MAIPÚ,Rafael Riesco / esq. 1� Transversal,3,I02I;I10R;I10NR,-70.751076,-33.496300
3,PI725,I10,FLXJ-25,6384,18,26,2025-10-12 19:01:30.454787,19:01,4883,L-13-68-5-OP,MAIPÚ,Rafael Riesco / esq. 1� Transversal,3,I02I;I10R;I10NR,-70.751076,-33.496300
4,PI725,I02,FLXY-79,4575,12,16,2025-10-12 19:01:30.454789,19:01,4883,L-13-68-5-OP,MAIPÚ,Rafael Riesco / esq. 1� Transversal,3,I02I;I10R;I10NR,-70.751076,-33.496300

Podemos notar al revisar este DataFrame, en la columna 'servicios', que todos los códigos de micro tienen una letra al final (Sabemos que puede ser N, C, E, V) pero también las hay en casos que no corresponden. Tomemos un paradero como ejemplo:

In [10]:
# PARADERO DE EJEMPLO
paradero_ejemplo = micro_paradero[micro_paradero['bus_stop_code'] == 'PJ607'].head(1)
print(f'Los recorridos que pasan por este paradero en la fila: {paradero_ejemplo['servicios']}')
print('Esto no tiene sentido, no existe la J01R y la ruta corta corresponde a la J01c')

Los recorridos que pasan por este paradero en la fila: 2852    J01R;J01cR
Name: servicios, dtype: object
Esto no tiene sentido, no existe la J01R y la ruta corta corresponde a la J01c

En consecuencia, es necesario que los datos correspondientes a los recorridos sean los correctos:

In [11]:
micro_limpio = micro_paradero.copy()
micro_limpio['servicios'] = micro_limpio['servicios'].str.replace(r'([IR])(?=;|$)', '', regex=True)
micro_exp = micro_limpio['servicios'].str.split(';', expand=True)

micro_exp = micro_exp.apply(lambda x: pd.Series(x.unique()), axis=1)
micro_exp = micro_exp.drop([21], axis=1)
micro_exp

,0,1,2,3,4,5,6,7,8,9,...,11,12,13,14,15,16,17,18,19,20
0,B12,B12c,B33,None,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,B12,B12c,B33,None,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,I02,I10,I10N,None,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,I02,I10,I10N,None,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,I02,I10,I10N,None,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
276619,209,209c,F03,F18,None,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
276620,209,209c,F03,F18,None,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
276621,209,209c,F03,F18,None,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
276622,209,209c,F03,F18,None,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
276623,209,209c,F03,F18,None,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
micro_limpio.head(3)

,bus_stop_code,route_id,bus_id,meters_distance,min_arrival_time,max_arrival_time,date,Hour_minute,id,codinfra,comuna,nombre_par,n_servicios,servicios,lan,lon
0,PB1013,B12,SKDG-90,7520,16,24,2025-10-12 19:01:28.530087,19:01,8983,L-6-39-30-OP,QUILICURA,San Ignacio / esq. Galvarino,3,B12;B12c;B33,-70.705935,-33.331142
1,PB1013,B33,SKPP-55,2951,8,10,2025-10-12 19:01:28.530094,19:01,8983,L-6-39-30-OP,QUILICURA,San Ignacio / esq. Galvarino,3,B12;B12c;B33,-70.705935,-33.331142
2,PI725,I10,FLXK-93,2315,7,9,2025-10-12 19:01:30.454781,19:01,4883,L-13-68-5-OP,MAIPÚ,Rafael Riesco / esq. 1� Transversal,3,I02;I10;I10N,-70.751076,-33.496300

In [13]:
recorridos_limpios = pd.concat([micro_limpio, micro_exp], axis=1)
recorridos_limpios.columns

Index([   'bus_stop_code',         'route_id',           'bus_id',
        'meters_distance', 'min_arrival_time', 'max_arrival_time',
                   'date',      'Hour_minute',               'id',
               'codinfra',           'comuna',       'nombre_par',
            'n_servicios',        'servicios',              'lan',
                    'lon',                  0,                  1,
                        2,                  3,                  4,
                        5,                  6,                  7,
                        8,                  9,                 10,
                       11,                 12,                 13,
                       14,                 15,                 16,
                       17,                 18,                 19,
                       20],
      dtype='object')

In [ ]:
#recorridos_limpios.drop_duplicates(keep='first', inplace=True, ignore_index=True)
recorridos_limpios.head(1)

,bus_stop_code,route_id,bus_id,meters_distance,min_arrival_time,max_arrival_time,date,Hour_minute,id,codinfra,...,11,12,13,14,15,16,17,18,19,20
0,PB1013,B12,SKDG-90,7520,16,24,2025-10-12 19:01:28.530087,19:01,8983,L-6-39-30-OP,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,PB1013,B33,SKPP-55,2951,8,10,2025-10-12 19:01:28.530094,19:01,8983,L-6-39-30-OP,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,PI725,I10,FLXK-93,2315,7,9,2025-10-12 19:01:30.454781,19:01,4883,L-13-68-5-OP,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,PI725,I10,FLXJ-25,6384,18,26,2025-10-12 19:01:30.454787,19:01,4883,L-13-68-5-OP,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,PI725,I02,FLXY-79,4575,12,16,2025-10-12 19:01:30.454789,19:01,4883,L-13-68-5-OP,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
276609,PF561,124,SRVF-96,3572,10,14,2025-10-20 22:30:35.298381,22:00,10837,L-34-73-30-OP,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
276610,PF561,124,STHC-95,6421,16,24,2025-10-20 22:30:35.298382,22:00,10837,L-34-73-30-OP,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
276611,PG2030,286,SHXB-27,1025,0,3,2025-10-20 22:30:37.134566,22:00,11539,L-23-65-11-SN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
276612,PG2030,286,SHCV-37,5344,11,15,2025-10-20 22:30:37.134570,22:00,11539,L-23-65-11-SN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
276613,PE120,E01,VKJY-49,3093,9,13,2025-10-20 22:30:39.048278,22:00,1276,L-22-29-7-OP,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [18]:
recorrido_poniente = recorridos_limpios[recorridos_limpios['comuna'].isin(['QUINTA NORMAL', 'CERRO NAVIA', 'MAIPÚ', 'CERRILLOS',
                                                     'ESTACIÓN CENTRAL', 'PUDAHUEL', 'RENCA', 'LO PRADO',
                                                     'PADRE HURTADO'])]
recorrido_poniente['comuna'].value_counts()

comuna
MAIPÚ               22638
PUDAHUEL             9633
ESTACIÓN CENTRAL     8863
QUINTA NORMAL        7829
RENCA                7359
CERRO NAVIA          7328
CERRILLOS            6190
LO PRADO             4289
PADRE HURTADO         369
Name: count, dtype: int64

In [19]:
# COMUNAS ORIENTE
recorrido_oriente = recorridos_limpios[recorridos_limpios['comuna'].isin(['PROVIDENCIA', 'ÑUÑOA', 'LA REINA', 'LAS CONDES',
                                                                  'VITACURA', 'LO BARNECHEA', 'PEÑALOLÉN', 'MACUL',
                                                                  'LA FLORIDA', 'PUENTE ALTO'])]
recorrido_oriente['comuna'].value_counts()

comuna
PUENTE ALTO     21526
LAS CONDES      14384
LA FLORIDA      14117
PEÑALOLÉN       10397
ÑUÑOA            8392
PROVIDENCIA      7062
LA REINA         5919
MACUL            5592
VITACURA         4442
LO BARNECHEA     3115
Name: count, dtype: int64

In [21]:
# SECTOR SUR
recorrido_sur = recorridos_limpios[recorridos_limpios['comuna'].isin(['PEDRO AGUIRRE CERDA', 'SAN MIGUEL',
                                                              'SAN JOAQUÍN', 'LO ESPEJO', 'LA CISTERNA',
                                                              'LA GRANJA', 'SAN RAMÓN', 'EL BOSQUE',
                                                              'SAN BERNARDO', 'LA CISTERNA'])]
recorrido_sur['comuna'].value_counts()

comuna
SAN BERNARDO           10384
EL BOSQUE               6649
LA GRANJA               5157
LO ESPEJO               5011
LA CISTERNA             4935
SAN MIGUEL              4650
SAN RAMÓN               4203
PEDRO AGUIRRE CERDA     3882
SAN JOAQUÍN             3719
Name: count, dtype: int64

In [20]:
# SECTOR NORTE
recorrido_norte = recorridos_limpios[recorridos_limpios['comuna'].isin(['CONCHALÍ', 'HUECHURABA', 'INDEPENDENCIA', 'RECOLETA', 'QUILICURA'])]
recorrido_norte['comuna'].value_counts()

comuna
QUILICURA        9887
CONCHALÍ         6219
RECOLETA         5868
HUECHURABA       4303
INDEPENDENCIA    3837
Name: count, dtype: int64

In [ ]:
mediana_tiempo_norte = recorrido_norte.groupby(by='Hour_minute').agg({'meters_distance': 'median'})
mediana_tiempo_sur = recorrido_sur.groupby(by='Hour_minute').agg({'meters_distance': 'median'})
mediana_tiempo_oriente = recorrido_oriente.groupby(by='Hour_minute').agg({'meters_distance': 'median'})
mediana_tiempo_poniente = recorrido_poniente.groupby(by='Hour_minute').agg({'meters_distance': 'median'})
mediana_oriente_poniente = pd.merge(mediana_tiempo_oriente, mediana_tiempo_poniente, on='Hour_minute', how='outer')
mediana_oriente_poniente = mediana_oriente_poniente.set_axis(['Sector Oriente', 'Sector Poniente'], axis= 1)
mediana_norte_sur = pd.merge(mediana_tiempo_norte, mediana_tiempo_sur, on='Hour_minute', how='outer')
mediana_norte_sur = mediana_norte_sur.set_axis(['Sector Norte', 'Sector Sur'], axis= 1)
mediana_por_sector = pd.merge(mediana_norte_sur, mediana_oriente_poniente, on='Hour_minute', how='outer')
mediana_por_sector.drop(mediana_por_sector.index[2], inplace=True)
mediana_por_sector

             Sector Norte  Sector Sur  Sector Oriente  Sector Poniente
Hour_minute
06:00              4097.0      3473.0          4102.0           4750.0
08:00              2672.0      2568.0          2438.0           3028.0
10:00              2773.5      2809.0          2490.0           3194.0
12:00              2836.0      2814.0          2691.0           3117.0
14:00              2585.0      2718.0          2590.0           2964.0
16:00              2950.5      2789.0          2635.0           2965.5
18:00              2400.5      2552.0          2369.0           2733.5
19:01              3895.0      3820.0          4012.0           4420.0
20:00              2758.0      2825.5          2721.0           3017.0
22:00              3454.0      3487.0          3440.0           3677.0