# EXTRACCIÓN DE DATA

In [29]:
# librerías a utilizar
import pandas as pd
import json
from pathlib import Path
from datetime import datetime, timedelta, date

In [7]:
# Creamos funcion que añada nuevos datos al dataframe unificado 
def anadir_datos(nuevos_datos, ruta):
    # Dataframe de los datos nuevos
    df_nuevos_datos = pd.concat(nuevos_datos, ignore_index=True)
    # Si ya tenemos datos en dicha fecha:
    if ruta.exists():
        # Abrimos los datos ya existentes
        datos_guardados = pd.read_csv(ruta)
        # Les añadimos los nuevos datos recolectados
        nuevo_csv = pd.concat([datos_guardados, df_nuevos_datos], ignore_index=True)
        # volvemos a guardar en la ruta que estaban los datos ya existentes
        nuevo_csv.to_csv(ruta, index=False, encoding='utf-8')
    else:
        # si no teníamos datos en dicha fecha
        nuevo_csv = df_nuevos_datos
        # agregamos los datos a la ruta 
        nuevo_csv.to_csv(ruta, index=False, encoding='utf-8')
    return nuevo_csv

In [8]:
# Creamos las rutas a la carpeta de la micro y metro:
carpeta_bus = Path('buses_outputs')
carpeta_metro = Path('metro_outputs')
# Creamos las carpetas para guardar los datos:
csv_unificado_micro = Path('csv_unificado_micro')
csv_unificado_micro.mkdir(exist_ok=True)
csv_unificado_metro = Path('csv_unificado_metro')
csv_unificado_metro.mkdir(exist_ok=True)
# Determinamos ruta para CSV's unificados
ruta_unificada_micro = csv_unificado_micro / 'datos_unificados_micro.csv'
ruta_unificada_metro = csv_unificado_metro / 'datos_unificados_metro.csv'
# Determinamos formato de tiempo que tienen los distintos csv
tiempo_hora_minuto = '%d-%m-%Y-%H-%M'
# Determinamos fecha inicial de extracción
fecha_inicio = date(2025, 10, 12)
print(f'La fecha de inicio para la extracción de datos es: {fecha_inicio}')

La fecha de inicio para la extracción de datos es: 2025-10-12

In [9]:
# Fecha en la que empezamos la extracción
fecha_actual = fecha_inicio
# Para los datos de la micro
info_df_diario = []
# Enlistamos los datos de 'buses_outputs'
recorrer = list(carpeta_bus.glob('*csv'))
# diccionario micros para ver si faltan agregar datos de un día
micro_dict = dict()
# Los recorremos para empezar a crear los DataFrame
for i in range(len(recorrer)): 
    # Ponemos en el formato de fecha de los datos extraídos: día, mes y año
    fecha_actual_formato = fecha_actual.strftime('%d-%m-%Y')
    print(f'Recolectando datos de las micros del día {fecha_actual_formato}')
    # Nos quedamos con la fecha del archivo que estamos leyendo
    archivo_fecha = recorrer[i].stem[6:]
    try: 
        # Si el archivo de esta iteración es valor de la llave de la fecha actual
        if archivo_fecha in micro_dict[fecha_actual_formato]:
            continue
        else:
            # si no lo es, lo añadimos
            micro_dict[fecha_actual_formato].add(archivo_fecha)
    # Si esa llave no existía (no habíamos revisado nada de ese día), la creamos
    except KeyError:
        # La creamos en un set para hacer más fácil su búsqueda después
        micro_dict[fecha_actual_formato] = {f'{archivo_fecha}'}
    # Convertimos la fecha del archivo al formato tiempo_hora_minuto
    hora_minuto = datetime.strptime(archivo_fecha, tiempo_hora_minuto)
    # Leemos el csv actual
    print(f'Recolectando datos de las: {hora_minuto.hour:02d}:{hora_minuto.minute:02d}')
    dataframe_archivo = pd.read_csv(recorrer[i], encoding='utf-8')
    # Creamos una columna que incluya la hora y el minuto
    dataframe_archivo['Hour_minute'] = f'{hora_minuto.hour:02d}:{hora_minuto.minute:02d}'
    # añadimos el df creado a nuestra lista de información por día
    info_df_diario.append(dataframe_archivo)
    try:
        # Si la fecha actual no está en el siguiente elemento, se acabaron los datos del
        # día y debemos guardar todo lo recolectado
        if fecha_actual_formato not in recorrer[i+1].stem:
            # creamos la ruta donde guardaremos los datos
            anadir_datos(info_df_diario, ruta_unificada_micro)
            # Vaciamos la info del día pues vamos a cambiarlo
            info_df_diario = []
            # Pasamos al día siguiente
            fecha_actual += timedelta(days=1)

    # Si llegamos al final de la lista no se podrá hacer i+1
    except IndexError as error:
        # creamos ruta para el último día de datos
        anadir_datos(info_df_diario, ruta_unificada_micro)
        # Vaciamos info del día
        info_df_diario = []

Recolectando datos de las micros del día 12-10-2025
Recolectando datos de las: 19:01
Recolectando datos de las micros del día 12-10-2025
Recolectando datos de las: 20:00
Recolectando datos de las micros del día 12-10-2025
Recolectando datos de las: 22:00
Recolectando datos de las micros del día 13-10-2025
Recolectando datos de las: 06:00
Recolectando datos de las micros del día 13-10-2025
Recolectando datos de las: 08:00
Recolectando datos de las micros del día 13-10-2025
Recolectando datos de las: 10:00
Recolectando datos de las micros del día 13-10-2025
Recolectando datos de las: 12:00
Recolectando datos de las micros del día 13-10-2025
Recolectando datos de las: 14:00
Recolectando datos de las micros del día 13-10-2025
Recolectando datos de las: 16:00
Recolectando datos de las micros del día 13-10-2025
Recolectando datos de las: 18:00
Recolectando datos de las micros del día 13-10-2025
Recolectando datos de las: 20:00
Recolectando datos de las micros del día 13-10-2025
Recolectando datos de las: 22:00
Recolectando datos de las micros del día 14-10-2025
Recolectando datos de las: 06:00
Recolectando datos de las micros del día 14-10-2025
Recolectando datos de las: 08:00
Recolectando datos de las micros del día 14-10-2025
Recolectando datos de las: 10:00
Recolectando datos de las micros del día 14-10-2025
Recolectando datos de las: 12:00
Recolectando datos de las micros del día 14-10-2025
Recolectando datos de las: 14:00
Recolectando datos de las micros del día 14-10-2025
Recolectando datos de las: 16:00
Recolectando datos de las micros del día 14-10-2025
Recolectando datos de las: 18:00
Recolectando datos de las micros del día 14-10-2025
Recolectando datos de las: 20:00
Recolectando datos de las micros del día 14-10-2025
Recolectando datos de las: 22:00
Recolectando datos de las micros del día 15-10-2025
Recolectando datos de las: 06:00
Recolectando datos de las micros del día 15-10-2025
Recolectando datos de las: 08:00
Recolectando datos de las micros del día 15-10-2025
Recolectando datos de las: 10:00
Recolectando datos de las micros del día 15-10-2025
Recolectando datos de las: 12:00
Recolectando datos de las micros del día 15-10-2025
Recolectando datos de las: 14:00
Recolectando datos de las micros del día 15-10-2025
Recolectando datos de las: 16:00
Recolectando datos de las micros del día 15-10-2025
Recolectando datos de las: 18:00
Recolectando datos de las micros del día 15-10-2025
Recolectando datos de las: 20:00
Recolectando datos de las micros del día 15-10-2025
Recolectando datos de las: 22:00
Recolectando datos de las micros del día 16-10-2025
Recolectando datos de las: 06:00
Recolectando datos de las micros del día 16-10-2025
Recolectando datos de las: 08:00
Recolectando datos de las micros del día 16-10-2025
Recolectando datos de las: 10:00
Recolectando datos de las micros del día 16-10-2025
Recolectando datos de las: 12:00
Recolectando datos de las micros del día 16-10-2025
Recolectando datos de las: 14:00
Recolectando datos de las micros del día 16-10-2025
Recolectando datos de las: 16:00
Recolectando datos de las micros del día 16-10-2025
Recolectando datos de las: 18:00
Recolectando datos de las micros del día 16-10-2025
Recolectando datos de las: 20:00
Recolectando datos de las micros del día 16-10-2025
Recolectando datos de las: 22:00
Recolectando datos de las micros del día 17-10-2025
Recolectando datos de las: 06:00
Recolectando datos de las micros del día 17-10-2025
Recolectando datos de las: 08:40
Recolectando datos de las micros del día 17-10-2025
Recolectando datos de las: 10:00
Recolectando datos de las micros del día 17-10-2025
Recolectando datos de las: 12:00
Recolectando datos de las micros del día 17-10-2025
Recolectando datos de las: 14:00
Recolectando datos de las micros del día 17-10-2025
Recolectando datos de las: 16:00
Recolectando datos de las micros del día 17-10-2025
Recolectando datos de las: 18:00
Recolectando datos de las micros del día 17-10-2025
Recolectando datos de las: 20:00
Recolectando datos de las micros del día 17-10-2025
Recolectando datos de las: 22:00
Recolectando datos de las micros del día 18-10-2025
Recolectando datos de las: 06:00
Recolectando datos de las micros del día 18-10-2025
Recolectando datos de las: 08:00
Recolectando datos de las micros del día 18-10-2025
Recolectando datos de las: 10:00
Recolectando datos de las micros del día 18-10-2025
Recolectando datos de las: 12:00
Recolectando datos de las micros del día 18-10-2025
Recolectando datos de las: 14:00
Recolectando datos de las micros del día 18-10-2025
Recolectando datos de las: 16:00
Recolectando datos de las micros del día 18-10-2025
Recolectando datos de las: 18:00
Recolectando datos de las micros del día 18-10-2025
Recolectando datos de las: 20:00
Recolectando datos de las micros del día 18-10-2025
Recolectando datos de las: 22:00
Recolectando datos de las micros del día 19-10-2025
Recolectando datos de las: 06:00
Recolectando datos de las micros del día 19-10-2025
Recolectando datos de las: 08:00
Recolectando datos de las micros del día 19-10-2025
Recolectando datos de las: 10:00
Recolectando datos de las micros del día 19-10-2025
Recolectando datos de las: 12:00
Recolectando datos de las micros del día 19-10-2025
Recolectando datos de las: 14:00
Recolectando datos de las micros del día 19-10-2025
Recolectando datos de las: 16:00
Recolectando datos de las micros del día 19-10-2025
Recolectando datos de las: 18:00
Recolectando datos de las micros del día 19-10-2025
Recolectando datos de las: 20:00
Recolectando datos de las micros del día 19-10-2025
Recolectando datos de las: 22:00

In [11]:
# Añadimos los datos diarios del metro
df_metro_diario = []
# Partimos con la fecha de inicio
fecha_actual_metro = fecha_inicio
datos = list(carpeta_metro.glob('*csv'))
# creamos diccionario para ver si faltan agregar los datos de un día
metro_dict = dict()
for i in range(len(datos)):
    # Trabajamos la fecha según como salen los datos de carpeta_metro
    formato_metro = fecha_actual_metro.strftime('%d-%m-%Y')
    print(f'Recolectando datos del metro del día: {formato_metro}')
    fecha_a_revisar = datos[i].stem[6:]
    try: 
        if fecha_a_revisar in metro_dict[formato_metro]:
            continue
        else:
            metro_dict[formato_metro].add(fecha_a_revisar)
    except KeyError:
        metro_dict[formato_metro] = {f'{fecha_a_revisar}'}
    hora_minuto = datetime.strptime(fecha_a_revisar, tiempo_hora_minuto)
    print(f'Recolectando datos de las: {hora_minuto.hour:02d}:{hora_minuto.minute:02d}')
    dataframe_actual = pd.read_csv(datos[i], encoding='utf-8')
    dataframe_actual['Hora_minuto'] = f'{hora_minuto.hour:02d}:{hora_minuto.minute:02d}'
    df_metro_diario.append(dataframe_actual)
    try:
        # Si la fecha actual no está en el siguiente elemento, se acabaron los datos del
        # día y debemos guardar todo lo recolectado
        if formato_metro not in datos[i+1].stem:
            # creamos la ruta donde guardaremos los datos
            anadir_datos(df_metro_diario, ruta_unificada_metro)
            df_metro_diario = []
            # Sumamos un día a la fecha actual
            fecha_actual_metro += timedelta(days=1)
    # Si llegamos al final de la lista no se podrá hacer i+1
    except IndexError as error:
        # creamos ruta para el último día de datos
        anadir_datos(df_metro_diario, ruta_unificada_metro)
        df_metro_diario = []

Recolectando datos del metro del día: 12-10-2025
Recolectando datos de las: 17:07
Recolectando datos del metro del día: 12-10-2025
Recolectando datos de las: 18:30
Recolectando datos del metro del día: 12-10-2025
Recolectando datos de las: 19:30
Recolectando datos del metro del día: 12-10-2025
Recolectando datos de las: 20:30
Recolectando datos del metro del día: 12-10-2025
Recolectando datos de las: 21:30
Recolectando datos del metro del día: 12-10-2025
Recolectando datos de las: 22:30
Recolectando datos del metro del día: 13-10-2025
Recolectando datos de las: 06:30
Recolectando datos del metro del día: 13-10-2025
Recolectando datos de las: 07:30
Recolectando datos del metro del día: 13-10-2025
Recolectando datos de las: 08:30
Recolectando datos del metro del día: 13-10-2025
Recolectando datos de las: 09:30
Recolectando datos del metro del día: 13-10-2025
Recolectando datos de las: 10:30
Recolectando datos del metro del día: 13-10-2025
Recolectando datos de las: 11:30
Recolectando datos del metro del día: 13-10-2025
Recolectando datos de las: 12:30
Recolectando datos del metro del día: 13-10-2025
Recolectando datos de las: 13:30
Recolectando datos del metro del día: 13-10-2025
Recolectando datos de las: 14:30
Recolectando datos del metro del día: 13-10-2025
Recolectando datos de las: 15:30
Recolectando datos del metro del día: 13-10-2025
Recolectando datos de las: 16:30
Recolectando datos del metro del día: 13-10-2025
Recolectando datos de las: 17:30
Recolectando datos del metro del día: 13-10-2025
Recolectando datos de las: 18:30
Recolectando datos del metro del día: 13-10-2025
Recolectando datos de las: 19:30
Recolectando datos del metro del día: 13-10-2025
Recolectando datos de las: 20:30
Recolectando datos del metro del día: 13-10-2025
Recolectando datos de las: 21:30
Recolectando datos del metro del día: 13-10-2025
Recolectando datos de las: 22:30
Recolectando datos del metro del día: 14-10-2025
Recolectando datos de las: 06:30
Recolectando datos del metro del día: 14-10-2025
Recolectando datos de las: 07:30
Recolectando datos del metro del día: 14-10-2025
Recolectando datos de las: 08:30
Recolectando datos del metro del día: 14-10-2025
Recolectando datos de las: 09:30
Recolectando datos del metro del día: 14-10-2025
Recolectando datos de las: 10:30
Recolectando datos del metro del día: 14-10-2025
Recolectando datos de las: 11:30
Recolectando datos del metro del día: 14-10-2025
Recolectando datos de las: 12:30
Recolectando datos del metro del día: 14-10-2025
Recolectando datos de las: 13:30
Recolectando datos del metro del día: 14-10-2025
Recolectando datos de las: 14:30
Recolectando datos del metro del día: 14-10-2025
Recolectando datos de las: 15:30
Recolectando datos del metro del día: 14-10-2025
Recolectando datos de las: 16:30
Recolectando datos del metro del día: 14-10-2025
Recolectando datos de las: 17:30
Recolectando datos del metro del día: 14-10-2025
Recolectando datos de las: 18:30
Recolectando datos del metro del día: 14-10-2025
Recolectando datos de las: 19:30
Recolectando datos del metro del día: 14-10-2025
Recolectando datos de las: 20:30
Recolectando datos del metro del día: 14-10-2025
Recolectando datos de las: 21:30
Recolectando datos del metro del día: 14-10-2025
Recolectando datos de las: 22:30
Recolectando datos del metro del día: 15-10-2025
Recolectando datos de las: 06:30
Recolectando datos del metro del día: 15-10-2025
Recolectando datos de las: 07:30
Recolectando datos del metro del día: 15-10-2025
Recolectando datos de las: 09:30
Recolectando datos del metro del día: 15-10-2025
Recolectando datos de las: 10:30
Recolectando datos del metro del día: 15-10-2025
Recolectando datos de las: 11:30
Recolectando datos del metro del día: 15-10-2025
Recolectando datos de las: 12:30
Recolectando datos del metro del día: 15-10-2025
Recolectando datos de las: 13:30
Recolectando datos del metro del día: 15-10-2025
Recolectando datos de las: 14:30
Recolectando datos del metro del día: 15-10-2025
Recolectando datos de las: 15:30
Recolectando datos del metro del día: 15-10-2025
Recolectando datos de las: 16:30
Recolectando datos del metro del día: 15-10-2025
Recolectando datos de las: 17:30
Recolectando datos del metro del día: 15-10-2025
Recolectando datos de las: 18:30
Recolectando datos del metro del día: 15-10-2025
Recolectando datos de las: 19:30
Recolectando datos del metro del día: 15-10-2025
Recolectando datos de las: 20:30
Recolectando datos del metro del día: 15-10-2025
Recolectando datos de las: 21:30
Recolectando datos del metro del día: 15-10-2025
Recolectando datos de las: 22:30
Recolectando datos del metro del día: 16-10-2025
Recolectando datos de las: 06:30
Recolectando datos del metro del día: 16-10-2025
Recolectando datos de las: 07:30
Recolectando datos del metro del día: 16-10-2025
Recolectando datos de las: 08:30
Recolectando datos del metro del día: 16-10-2025
Recolectando datos de las: 09:30
Recolectando datos del metro del día: 16-10-2025
Recolectando datos de las: 10:30
Recolectando datos del metro del día: 16-10-2025
Recolectando datos de las: 11:30
Recolectando datos del metro del día: 16-10-2025
Recolectando datos de las: 12:30
Recolectando datos del metro del día: 16-10-2025
Recolectando datos de las: 13:30
Recolectando datos del metro del día: 16-10-2025
Recolectando datos de las: 14:30
Recolectando datos del metro del día: 16-10-2025
Recolectando datos de las: 15:30
Recolectando datos del metro del día: 16-10-2025
Recolectando datos de las: 16:30
Recolectando datos del metro del día: 16-10-2025
Recolectando datos de las: 17:30
Recolectando datos del metro del día: 16-10-2025
Recolectando datos de las: 18:30
Recolectando datos del metro del día: 16-10-2025
Recolectando datos de las: 19:30
Recolectando datos del metro del día: 16-10-2025
Recolectando datos de las: 20:30
Recolectando datos del metro del día: 16-10-2025
Recolectando datos de las: 21:30
Recolectando datos del metro del día: 16-10-2025
Recolectando datos de las: 22:30
Recolectando datos del metro del día: 17-10-2025
Recolectando datos de las: 06:30
Recolectando datos del metro del día: 17-10-2025
Recolectando datos de las: 07:30
Recolectando datos del metro del día: 17-10-2025
Recolectando datos de las: 08:30
Recolectando datos del metro del día: 17-10-2025
Recolectando datos de las: 09:30
Recolectando datos del metro del día: 17-10-2025
Recolectando datos de las: 10:30
Recolectando datos del metro del día: 17-10-2025
Recolectando datos de las: 11:30
Recolectando datos del metro del día: 17-10-2025
Recolectando datos de las: 12:30
Recolectando datos del metro del día: 17-10-2025
Recolectando datos de las: 13:30
Recolectando datos del metro del día: 17-10-2025
Recolectando datos de las: 14:30
Recolectando datos del metro del día: 17-10-2025
Recolectando datos de las: 15:30
Recolectando datos del metro del día: 17-10-2025
Recolectando datos de las: 16:30
Recolectando datos del metro del día: 17-10-2025
Recolectando datos de las: 17:30
Recolectando datos del metro del día: 17-10-2025
Recolectando datos de las: 18:30
Recolectando datos del metro del día: 17-10-2025
Recolectando datos de las: 19:30
Recolectando datos del metro del día: 17-10-2025
Recolectando datos de las: 20:30
Recolectando datos del metro del día: 17-10-2025
Recolectando datos de las: 21:30
Recolectando datos del metro del día: 17-10-2025
Recolectando datos de las: 22:30
Recolectando datos del metro del día: 18-10-2025
Recolectando datos de las: 06:30
Recolectando datos del metro del día: 18-10-2025
Recolectando datos de las: 07:30
Recolectando datos del metro del día: 18-10-2025
Recolectando datos de las: 08:30
Recolectando datos del metro del día: 18-10-2025
Recolectando datos de las: 09:30
Recolectando datos del metro del día: 18-10-2025
Recolectando datos de las: 10:30
Recolectando datos del metro del día: 18-10-2025
Recolectando datos de las: 11:30
Recolectando datos del metro del día: 18-10-2025
Recolectando datos de las: 12:30
Recolectando datos del metro del día: 18-10-2025
Recolectando datos de las: 13:30
Recolectando datos del metro del día: 18-10-2025
Recolectando datos de las: 14:30
Recolectando datos del metro del día: 18-10-2025
Recolectando datos de las: 15:30
Recolectando datos del metro del día: 18-10-2025
Recolectando datos de las: 16:30
Recolectando datos del metro del día: 18-10-2025
Recolectando datos de las: 17:30
Recolectando datos del metro del día: 18-10-2025
Recolectando datos de las: 18:30
Recolectando datos del metro del día: 18-10-2025
Recolectando datos de las: 19:30
Recolectando datos del metro del día: 18-10-2025
Recolectando datos de las: 20:30
Recolectando datos del metro del día: 18-10-2025
Recolectando datos de las: 21:30
Recolectando datos del metro del día: 18-10-2025
Recolectando datos de las: 22:30
Recolectando datos del metro del día: 19-10-2025
Recolectando datos de las: 06:30
Recolectando datos del metro del día: 19-10-2025
Recolectando datos de las: 07:30
Recolectando datos del metro del día: 19-10-2025
Recolectando datos de las: 08:30
Recolectando datos del metro del día: 19-10-2025
Recolectando datos de las: 09:30
Recolectando datos del metro del día: 19-10-2025
Recolectando datos de las: 10:30
Recolectando datos del metro del día: 19-10-2025
Recolectando datos de las: 11:30
Recolectando datos del metro del día: 19-10-2025
Recolectando datos de las: 12:30
Recolectando datos del metro del día: 19-10-2025
Recolectando datos de las: 13:30
Recolectando datos del metro del día: 19-10-2025
Recolectando datos de las: 14:30
Recolectando datos del metro del día: 19-10-2025
Recolectando datos de las: 15:30
Recolectando datos del metro del día: 19-10-2025
Recolectando datos de las: 16:30
Recolectando datos del metro del día: 19-10-2025
Recolectando datos de las: 17:30
Recolectando datos del metro del día: 19-10-2025
Recolectando datos de las: 18:30
Recolectando datos del metro del día: 19-10-2025
Recolectando datos de las: 19:30
Recolectando datos del metro del día: 19-10-2025
Recolectando datos de las: 20:30
Recolectando datos del metro del día: 19-10-2025
Recolectando datos de las: 21:30
Recolectando datos del metro del día: 19-10-2025
Recolectando datos de las: 22:30

In [15]:
micro_data = pd.read_csv(ruta_unificada_micro)
metro_data = pd.read_csv(ruta_unificada_metro)

In [46]:
# Abrimos el archivo donde tenemos información importantes de los pasajeros
ruta_json = Path('data', 'Paraderos-Santiago-Chile.geojsonl.json')
datos = []
with open(ruta_json, 'r', encoding='utf-8-sig')as f:
    for archivo in f:
        datos.append(json.loads(archivo.strip()))
df_paradero = pd.json_normalize(datos)
df_paradero = df_paradero.rename(columns={'properties.ID': 'id', 
                            'properties.CODINFRA': 'codinfra',
                            'properties.SIMT': 'bus_stop_code',
                            'properties.COMUNA': 'comuna',
                            'properties.NOMBRE_PAR': 'nombre_par',
                            'properties.NSERVICIOS': 'n_servicios',
                            'properties.SERVICIOS': 'servicios',
                            'geometry.coordinates': 'coordinates'})
df_paradero = df_paradero[['id', 'codinfra', 'comuna', 'bus_stop_code', 'nombre_par', 'n_servicios', 'servicios', 'coordinates']]
df_paradero['comuna'] = df_paradero['comuna'].replace(
    {'CONCHAL�': 'CONCHALÍ',
    'ESTACI�N CENTRAL': 'ESTACIÓN CENTRAL',
    'MAIP�': 'MAIPÚ',
    'PE�ALOL�N': 'PEÑALOLÉN',
    'SAN JOAQU�N': 'SAN JOAQUÍN',
    'SAN RAM�N': 'SAN RAMÓN',
    '�U�OA': 'ÑUÑOA'
    })
df_paradero.head()

,id,codinfra,comuna,bus_stop_code,nombre_par,n_servicios,servicios,coordinates
0,11672,L-35-6-5-OP,PADRE HURTADO,PI1923,Cam. Bajos de Sta. Cruz / esq. El Muelle,1,I35I,"[-70.823088, -33.572525]"
1,11671,L-35-1-67-OP,PADRE HURTADO,PI1935,Cam. Sn. Alberto Hurtado / esq. Sn. Fco de Borja,1,I35I,"[-70.8189, -33.571649]"
2,11674,L-35-5-48-NS,PADRE HURTADO,PI1926,Avenida San Ignacio / esq. Cam. Sn. A. Hurtado,1,I35I,"[-70.818197, -33.57202]"
3,11693,L-35-5-49-SN,PADRE HURTADO,PI1925,Avenida San Ignacio / esq. Cam. Sn. A. Hurtado,1,I35R,"[-70.817967, -33.57187]"
4,11675,L-35-5-54-NS,PADRE HURTADO,PI1927,Avenida San Ignacio / esq. San Alberto,1,I35I,"[-70.816035, -33.574243]"

In [47]:
micro_paradero = pd.merge(micro_data, df_paradero, on= 'bus_stop_code', how='inner')
micro_paradero.head()

,bus_stop_code,route_id,bus_id,meters_distance,min_arrival_time,max_arrival_time,date,X,Y,Hour_minute,id,codinfra,comuna,nombre_par,n_servicios,servicios,coordinates
0,PB1013,B12,SKDG-90,7520,16,24,2025-10-12 19:01:28.530087,341227.257,6310702.634,19:01,8983,L-6-39-30-OP,QUILICURA,San Ignacio / esq. Galvarino,3,B12I;B12cR;B33I,"[-70.705935, -33.331142]"
1,PB1013,B33,SKPP-55,2951,8,10,2025-10-12 19:01:28.530094,341227.257,6310702.634,19:01,8983,L-6-39-30-OP,QUILICURA,San Ignacio / esq. Galvarino,3,B12I;B12cR;B33I,"[-70.705935, -33.331142]"
2,PI725,I10,FLXK-93,2315,7,9,2025-10-12 19:01:30.454781,337333.753,6292318.918,19:01,4883,L-13-68-5-OP,MAIPÚ,Rafael Riesco / esq. 1� Transversal,3,I02I;I10R;I10NR,"[-70.751076, -33.4963]"
3,PI725,I10,FLXJ-25,6384,18,26,2025-10-12 19:01:30.454787,337333.753,6292318.918,19:01,4883,L-13-68-5-OP,MAIPÚ,Rafael Riesco / esq. 1� Transversal,3,I02I;I10R;I10NR,"[-70.751076, -33.4963]"
4,PI725,I02,FLXY-79,4575,12,16,2025-10-12 19:01:30.454789,337333.753,6292318.918,19:01,4883,L-13-68-5-OP,MAIPÚ,Rafael Riesco / esq. 1� Transversal,3,I02I;I10R;I10NR,"[-70.751076, -33.4963]"

In [50]:
micro_paradero[['lan', 'lon']] = pd.DataFrame(micro_paradero['coordinates'].tolist(), index=micro_paradero.index)
micro_paradero.head()

,bus_stop_code,route_id,bus_id,meters_distance,min_arrival_time,max_arrival_time,date,X,Y,Hour_minute,id,codinfra,comuna,nombre_par,n_servicios,servicios,coordinates,lan,lon
0,PB1013,B12,SKDG-90,7520,16,24,2025-10-12 19:01:28.530087,341227.257,6310702.634,19:01,8983,L-6-39-30-OP,QUILICURA,San Ignacio / esq. Galvarino,3,B12I;B12cR;B33I,"[-70.705935, -33.331142]",-70.705935,-33.331142
1,PB1013,B33,SKPP-55,2951,8,10,2025-10-12 19:01:28.530094,341227.257,6310702.634,19:01,8983,L-6-39-30-OP,QUILICURA,San Ignacio / esq. Galvarino,3,B12I;B12cR;B33I,"[-70.705935, -33.331142]",-70.705935,-33.331142
2,PI725,I10,FLXK-93,2315,7,9,2025-10-12 19:01:30.454781,337333.753,6292318.918,19:01,4883,L-13-68-5-OP,MAIPÚ,Rafael Riesco / esq. 1� Transversal,3,I02I;I10R;I10NR,"[-70.751076, -33.4963]",-70.751076,-33.496300
3,PI725,I10,FLXJ-25,6384,18,26,2025-10-12 19:01:30.454787,337333.753,6292318.918,19:01,4883,L-13-68-5-OP,MAIPÚ,Rafael Riesco / esq. 1� Transversal,3,I02I;I10R;I10NR,"[-70.751076, -33.4963]",-70.751076,-33.496300
4,PI725,I02,FLXY-79,4575,12,16,2025-10-12 19:01:30.454789,337333.753,6292318.918,19:01,4883,L-13-68-5-OP,MAIPÚ,Rafael Riesco / esq. 1� Transversal,3,I02I;I10R;I10NR,"[-70.751076, -33.4963]",-70.751076,-33.496300

In [51]:
recorrido_poniente = micro_paradero[micro_paradero['comuna'].isin(['QUINTA NORMAL', 'CERRO NAVIA', 'MAIPÚ', 'CERRILLOS',
                                                     'ESTACIÓN CENTRAL', 'PUDAHUEL', 'RENCA', 'LO PRADO',
                                                     'PADRE HURTADO'])]
recorrido_poniente['comuna'].value_counts()

comuna
MAIPÚ               19480
PUDAHUEL             8404
ESTACIÓN CENTRAL     7517
QUINTA NORMAL        6864
RENCA                6476
CERRO NAVIA          6326
CERRILLOS            5237
LO PRADO             3787
PADRE HURTADO         322
Name: count, dtype: int64

In [52]:
# COMUNAS ORIENTE
recorrido_oriente = micro_paradero[micro_paradero['comuna'].isin(['PROVIDENCIA', 'ÑUÑOA', 'LA REINA', 'LAS CONDES',
                                                                  'VITACURA', 'LO BARNECHEA', 'PEÑALOLÉN', 'MACUL',
                                                                  'LA FLORIDA', 'PUENTE ALTO'])]
recorrido_oriente['comuna'].value_counts()

comuna
PUENTE ALTO     18776
LAS CONDES      12642
LA FLORIDA      12182
PEÑALOLÉN        8933
ÑUÑOA            7281
PROVIDENCIA      6249
LA REINA         5282
MACUL            4943
VITACURA         3843
LO BARNECHEA     2792
Name: count, dtype: int64

In [53]:
# SECTOR SUR
recorrido_sur = micro_paradero[micro_paradero['comuna'].isin(['PEDRO AGUIRRE CERDA', 'SAN MIGUEL',
                                                              'SAN JOAQUÍN', 'LO ESPEJO', 'LA CISTERNA',
                                                              'LA GRANJA', 'SAN RAMÓN', 'EL BOSQUE',
                                                              'SAN BERNARDO', 'LA CISTERNA'])]
recorrido_sur['comuna'].value_counts()

comuna
SAN BERNARDO           9075
EL BOSQUE              5694
LA GRANJA              4576
LA CISTERNA            4292
LO ESPEJO              4289
SAN MIGUEL             4031
SAN RAMÓN              3649
PEDRO AGUIRRE CERDA    3371
SAN JOAQUÍN            3270
Name: count, dtype: int64

In [54]:
# SECTOR NORTE
recorrido_norte = micro_paradero[micro_paradero['comuna'].isin(['CONCHALÍ', 'HUECHURABA', 'INDEPENDENCIA', 'RECOLETA', 'QUILICURA'])]
recorrido_norte['comuna'].value_counts()

comuna
QUILICURA        8651
CONCHALÍ         5408
RECOLETA         5076
HUECHURABA       3706
INDEPENDENCIA    3275
Name: count, dtype: int64